### ISSUE TITLE
Typo in the GR Ground Chart?

### ISSUE THREAD

**Issue by LuzDerSchluz** [Treelon/ptfs-charts#33]
1. In the file „IRFD Ground Chart“.svg, In the hot spot explaination, H1 is listed two times and H2 isnt mentioned at all. It might be that the 2nd entry is meant for H2

**Comment by cartermichaelatkins** [comment]
If you're talking about the Hot spot information box and the "HS" numbers there. I have fixed the issue and have put it in my Pull request along with other fixes.
