### ISSUE TITLE
Update airspace map

### ISSUE THREAD

**Issue by slpzc** [Treelon/ptfs-charts#42]
Due to the fact that Greater Rockford has been updated, Airspace is now obsolete and would like to see a new, updated version.

**Comment by slpzc** [comment]
up

**Comment by TG0171** [comment]
Yeah, GR has been updated, "Airspace" is obsolete, we need a new airspace map.

**Comment by slpzc** [comment]
> Yeah, GR has been updated, "Airspace" is obsolete, we need a new airspace map.

I sent Pull Requests and am still waiting for a response
